### ISSUE TITLE
 Authentication and Authorization

### ISSUE THREAD

**Issue by Kainat-0** [Kainat-0/GMS#1]
As a user, I want to be able to register for an account so that I can access the
system

- [ ] Task 1.1: Design registration form
- [ ] Task 1.2: Implement registration logic
- [ ] Task 1.3: Test registration functionality
